import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useDispatch } from 'react-redux';
import { useTranslation } from 'react-i18next';
import { authService } from '../../services/authService';
import { useAuth } from '../../hooks/useAuth';
import { setUser } from '../../store/slices/authSlice';
import { pushToast } from '../../store/slices/uiSlice';
import { ErrorBanner } from '../../components/Feedback';
export default function Profile(){const{t}=useTranslation();const{user}=useAuth();const dispatch=useDispatch();const queryClient=useQueryClient();const[form,setForm]=useState({name:user?.name||'',phone:user?.phone||'',birthday:user?.birthday?.slice(0,10)||''});const[pwForm,setPwForm]=useState({currentPassword:'',newPassword:''});const profileMutation=useMutation({mutationFn:authService.updateProfile,onSuccess:(data)=>{dispatch(setUser(data.user));queryClient.invalidateQueries({queryKey:['auth','me']});dispatch(pushToast(t('profile.updated')));}});const passwordMutation=useMutation({mutationFn:authService.updatePassword,onSuccess:()=>{dispatch(pushToast(t('profile.passwordUpdated')));setPwForm({currentPassword:'',newPassword:''});}});return <div className="container" style={{padding:'50px 24px',maxWidth:500}}><h1 style={{color:'var(--accent)',fontSize:30}}>{t('profile.title')}</h1><form onSubmit={(e)=>{e.preventDefault();profileMutation.mutate(form);}} className="card" style={{marginTop:20}}><ErrorBanner message={profileMutation.error?.message}/><div className="field"><label>{t('profile.fullName')}</label><input className="input" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>{t('profile.phone')}</label><input className="input" value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>{t('profile.birthday')}</label><input className="input" type="date" value={form.birthday} onChange={(e)=>setForm({...form,birthday:e.target.value})}/></div><button type="submit" className="btn btn-primary btn-block" disabled={profileMutation.isPending}>{t('profile.save')}</button></form><form onSubmit={(e)=>{e.preventDefault();passwordMutation.mutate(pwForm);}} className="card" style={{marginTop:20}}><h3 style={{marginBottom:12}}>{t('profile.changePassword')}</h3><ErrorBanner message={passwordMutation.error?.message}/><div className="field"><label>{t('profile.currentPassword')}</label><input className="input" type="password" required value={pwForm.currentPassword} onChange={(e)=>setPwForm({...pwForm,currentPassword:e.target.value})}/></div><div className="field"><label>{t('profile.newPassword')}</label><input className="input" type="password" required minLength={8} value={pwForm.newPassword} onChange={(e)=>setPwForm({...pwForm,newPassword:e.target.value})}/></div><button type="submit" className="btn btn-secondary btn-block" disabled={passwordMutation.isPending}>{t('profile.updatePassword')}</button></form></div>}
