export const PERMISSIONS = Object.freeze({
  APPOINTMENTS_VIEW_ALL: 'appointments:view_all',
  APPOINTMENTS_MANAGE: 'appointments:manage',
  WALKINS_CREATE: 'walkins:create',
  SCHEDULE_MANAGE: 'schedule:manage',
  CUSTOMERS_VIEW: 'customers:view',
  CUSTOMERS_MANAGE: 'customers:manage',
  STAFF_MANAGE: 'staff:manage',
  SERVICES_MANAGE: 'services:manage',
  CATEGORIES_MANAGE: 'categories:manage',
  PRODUCTS_MANAGE: 'products:manage',
  SUPPLIERS_MANAGE: 'suppliers:manage',
  PURCHASE_ORDERS_MANAGE: 'purchase_orders:manage',
  COUPONS_MANAGE: 'coupons:manage',
  TAXES_MANAGE: 'taxes:manage',
  LOCATIONS_MANAGE: 'locations:manage',
  PAYMENTS_TAKE_CASH: 'payments:take_cash',
  REPORTS_VIEW: 'reports:view',
  ROLES_MANAGE: 'roles:manage',
  SETTINGS_MANAGE: 'settings:manage',
  EMAIL_TEMPLATES_MANAGE: 'email_templates:manage',
  WHATSAPP_TEMPLATES_MANAGE: 'whatsapp_templates:manage',
  NOTIFICATIONS_MANAGE: 'notifications:manage',
  AUDIT_LOGS_VIEW: 'audit_logs:view',
  BACKUPS_MANAGE: 'backups:manage',
});
